# Generated by Django 5.2.17 on 2026-08-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=160)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual'), ('fixo', 'Valor fixo')], default='percentual', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usos_maximos', models.PositiveIntegerField(default=0, help_text='0 = ilimitado.')),
                ('usos', models.PositiveIntegerField(default=0, editable=False)),
                ('valido_de', models.DateTimeField(blank=True, null=True)),
                ('valido_ate', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pagamento confirmado'), ('aguardando_aprovacao', 'Aguardando aprovação do lojista'), ('aprovado', 'Aprovado'), ('em_separacao', 'Em separação'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('recusado', 'Recusado pelo lojista'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], db_index=True, default='rascunho', max_length=30)),
                ('nome_cliente', models.CharField(max_length=140)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefone_cliente', models.CharField(blank=True, max_length=20)),
                ('endereco_texto', models.CharField(blank=True, help_text='Cópia textual do endereço no momento da compra.', max_length=400)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto_assinatura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cupom', models.CharField(blank=True, max_length=40)),
                ('observacoes', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_recusa', models.CharField(blank=True, max_length=250)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=60)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(blank=True, max_length=30)),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('visivel_para_cliente', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_pedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento do pedido',
                'verbose_name_plural': 'eventos do pedido',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço efetivamente cobrado.', max_digits=10)),
                ('preco_cheio', models.DecimalField(decimal_places=2, help_text='Preço de tabela, antes do desconto.', max_digits=10)),
                ('recorrente', models.BooleanField(default=False)),
                ('frequencia_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('baixado_do_estoque', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
    ]
