# Generated by Django 5.2.17 on 2026-08-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='desconto_pix',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abatido quando o cliente fecha em Pix. Zerado se trocar de método.', max_digits=10),
        ),
    ]
