# Generated by Django 5.2.17 on 2026-08-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_produto_linha_alter_produto_unidade_variacaoproduto'),
        ('orders', '0003_pedido_desconto_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='catalog.variacaoproduto'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='variacao_rotulo',
            field=models.CharField(blank=True, help_text='Congelado na compra: 2kg, 500g…', max_length=30, verbose_name='apresentação'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='contato_pendente',
            field=models.BooleanField(default=False, help_text='Algum item saiu sem estoque suficiente na hora da separação.', verbose_name='atendente precisa falar com o cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens_em_falta',
            field=models.TextField(blank=True, help_text='Preenchido automaticamente quando o estoque não cobre o pedido.', verbose_name='itens em falta'),
        ),
    ]
