# Generated by Django 5.2.17 on 2026-08-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cidade_atendida',
            field=models.ForeignKey(blank=True, help_text='Define o frete e os dias de entrega.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos', to='shipping.cidade', verbose_name='cidade atendida'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='localidade',
            field=models.ForeignKey(blank=True, help_text='Ilha, povoado ou bairro com frete próprio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enderecos', to='shipping.localidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='aceita_contato_whatsapp',
            field=models.BooleanField(default=True, help_text='Para falar sobre o pedido quando faltar algum item.', verbose_name='pode ser chamado no WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, help_text='É por aqui que a loja avisa sobre falta de produto e entrega.', max_length=20, verbose_name='celular / WhatsApp'),
        ),
    ]
