# Generated by Django 5.2.17 on 2026-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_endereco_cidade_atendida_endereco_localidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desenvolvedor',
            field=models.BooleanField(default=False, help_text='Só quem mantém o sistema. O lojista usa o painel, nunca o admin.', verbose_name='acesso técnico (admin do Django)'),
        ),
    ]
