# Generated by Django 5.2.17 on 2026-08-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('catalog', '0007_produto_linha_alter_produto_unidade_variacaoproduto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='variacao',
            field=models.ForeignKey(blank=True, help_text='A apresentação escolhida: 2kg, 5kg, 500g…', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrinho', to='catalog.variacaoproduto'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto', 'variacao', 'recorrente', 'frequencia_dias')},
        ),
    ]
