# Generated by Django 5.2.17 on 2026-08-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssinanteNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'assinante da newsletter',
                'verbose_name_plural': 'assinantes da newsletter',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=140)),
                ('subtitulo', models.CharField(blank=True, max_length=220)),
                ('selo', models.CharField(blank=True, help_text='Etiqueta acima do título.', max_length=60)),
                ('imagem', models.ImageField(blank=True, upload_to='banners/')),
                ('cor_fundo', models.CharField(default='#D62B20', max_length=20)),
                ('texto_botao', models.CharField(blank=True, default='Ver catálogo', max_length=40)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('posicao', models.CharField(choices=[('hero', 'Carrossel principal'), ('faixa', 'Faixa promocional'), ('secundario', 'Banner secundário')], default='hero', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=80)),
                ('descricao', models.CharField(blank=True, max_length=160)),
                ('icone', models.CharField(default='truck', help_text='Nome do ícone SVG: truck, shield, refresh, zap, award, leaf.', max_length=40)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'diferencial',
                'verbose_name_plural': 'diferenciais',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('resumo', models.CharField(blank=True, max_length=220)),
                ('conteudo', models.TextField(help_text='Aceita HTML simples.')),
                ('publicado', models.BooleanField(default=True)),
                ('ordem_rodape', models.PositiveIntegerField(default=0, help_text='0 esconde do rodapé.')),
            ],
            options={
                'verbose_name': 'página institucional',
                'verbose_name_plural': 'páginas institucionais',
                'ordering': ['ordem_rodape', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome_loja', models.CharField(default='Veterinária AgroCampo', max_length=120)),
                ('chamada', models.CharField(default='Tudo para o campo e para quem você ama cuidar.', help_text='Frase principal exibida no hero da home.', max_length=200)),
                ('descricao', models.TextField(default='Ração, suplementos e equipamentos rurais com entrega rápida — e assinatura recorrente para nunca faltar o essencial.')),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('logo_claro', models.ImageField(blank=True, help_text='Versão para fundos escuros.', upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=250)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('anos_de_mercado', models.PositiveIntegerField(default=30)),
                ('frete_gratis_acima_de', models.DecimalField(decimal_places=2, default=199, max_digits=10, verbose_name='frete grátis acima de')),
                ('desconto_assinatura_padrao', models.PositiveIntegerField(default=10, verbose_name='desconto padrão da assinatura (%)')),
                ('desconto_pix', models.PositiveIntegerField(default=5, verbose_name='desconto no Pix (%)')),
                ('parcelas_maximas', models.PositiveIntegerField(default=3, verbose_name='máximo de parcelas sem juros')),
            ],
            options={
                'verbose_name': 'configuração da loja',
                'verbose_name_plural': 'configuração da loja',
            },
        ),
    ]
