# Generated by Django 5.2.17 on 2026-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cidade_uf',
            field=models.CharField(blank=True, max_length=90, verbose_name='cidade / UF'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='horario_atendimento',
            field=models.CharField(blank=True, default='Seg a sex, 8h às 18h · Sáb, 8h às 12h', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Figura recortada exibida no banner da home. Use PNG com fundo transparente. Vale como padrão quando o banner não tem imagem própria.', upload_to='site/', verbose_name='imagem de capa'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='rodape_sobre',
            field=models.TextField(blank=True, help_text='Se vazio, usa a descrição da loja.', verbose_name='texto do rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='topbar_icone',
            field=models.CharField(blank=True, default='🚚', max_length=8, verbose_name='emoji da faixa do topo'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='topbar_link_texto',
            field=models.CharField(blank=True, default='Rastrear meu pedido', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='topbar_link_url',
            field=models.CharField(blank=True, default='/pedidos/', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='topbar_mensagem',
            field=models.CharField(blank=True, default='Frete facilitado para toda a zona rural', help_text='Texto em destaque na barra escura acima do cabeçalho. Vazio esconde a barra.', max_length=120, verbose_name='mensagem da faixa do topo'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Só números com DDI, ex.: 5514997202800', max_length=40),
        ),
    ]
