# Generated by Django 5.2.17 on 2026-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_cep_siteconfig_cidade_uf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='anos_de_mercado',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ano_fundacao',
            field=models.PositiveIntegerField(default=2012, help_text='Conforme o CNPJ. O site calcula os anos de mercado a partir daqui.', verbose_name='ano de fundação'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blog_ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para esconder o blog do menu, do rodapé e da home. As URLs passam a responder 404.', verbose_name='blog ativo'),
        ),
    ]
