# Generated by Django 5.2.17 on 2026-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_siteconfig_anos_de_mercado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firebase · apiKey'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_app_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firebase · appId'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_auth_domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firebase · authDomain'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_messaging_sender_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='Firebase · messagingSenderId'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_project_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Firebase · projectId'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_service_account',
            field=models.TextField(blank=True, help_text='Credencial do Admin SDK, usada pelo servidor para disparar o push. Guardada só no banco e nunca exposta ao navegador.', verbose_name='Firebase · JSON da conta de serviço'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_storage_bucket',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firebase · storageBucket'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='firebase_vapid_key',
            field=models.CharField(blank=True, help_text='Console do Firebase › Cloud Messaging › Certificados push da Web.', max_length=250, verbose_name='Firebase · chave VAPID (par de chaves da Web Push)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pwa_convite_ativo',
            field=models.BooleanField(default=True, help_text='Mostra o convite de instalação para quem ainda não instalou.', verbose_name='convidar a instalar o app'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pwa_convite_segundos',
            field=models.PositiveIntegerField(default=30, help_text='Tempo de navegação antes de o convite aparecer.', verbose_name='esperar antes de convidar (segundos)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pwa_convite_texto',
            field=models.CharField(blank=True, default='Instale o app da AgroCampo e compre em dois toques.', max_length=160),
        ),
    ]
