# Generated by Django 5.2.17 on 2026-08-21 04:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfig_firebase_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='parcelas_maximas',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='frete_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('24.90'), help_text='Cobrado quando o pedido não atinge o mínimo do frete grátis.', max_digits=10, verbose_name='valor do frete'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='desconto_pix',
            field=models.PositiveIntegerField(default=0, help_text='Abatido do total quando o cliente escolhe Pix. Só prometa o que for cumprir: o valor aparece no checkout e é cobrado a menos.', verbose_name='desconto no Pix (%)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='frete_gratis_acima_de',
            field=models.DecimalField(decimal_places=2, default=199, help_text='Deixe 0 para nunca dar frete grátis.', max_digits=10, verbose_name='frete grátis acima de'),
        ),
    ]
