# Generated by Django 5.2.17 on 2026-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_siteconfig_parcelas_maximas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='aviso_entrega',
            field=models.TextField(blank=True, help_text='Aparece no carrinho e no checkout.', verbose_name='aviso geral de entrega'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='entrega_a_partir_de',
            field=models.TimeField(blank=True, help_text='Horário padrão. Cada cidade pode ter o seu.', null=True, verbose_name='entregas a partir de'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vitrine_bronze_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vitrine_bronze_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Linha Bronze', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vitrine_ouro_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vitrine_ouro_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Linha Ouro', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vitrine_prata_ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='vitrine_prata_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Linha Prata', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_flutuante',
            field=models.BooleanField(default=True, verbose_name='botão flutuante do WhatsApp'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_mensagem',
            field=models.CharField(blank=True, default='Olá! Vim pelo site e gostaria de tirar uma dúvida.', help_text='Texto já preenchido quando o cliente abre a conversa.', max_length=200),
        ),
    ]
