# Generated by Django 5.2.17 on 2026-08-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_produto_linha_alter_produto_unidade_variacaoproduto'),
        ('core', '0006_siteconfig_aviso_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='Só para a faixa de produtos: cada foto vira um link direto para o produto.', related_name='banners', to='catalog.produto', verbose_name='produtos da faixa'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='posicao',
            field=models.CharField(choices=[('hero', 'Carrossel principal'), ('faixa', 'Faixa promocional'), ('secundario', 'Banner secundário'), ('produtos', 'Faixa de produtos (fotos com link)')], default='hero', max_length=20),
        ),
    ]
