# Generated by Django 5.2.17 on 2026-08-22 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner_produtos_alter_banner_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo_altura',
            field=models.PositiveIntegerField(default=46, help_text='No celular ela encolhe sozinha. Entre 24 e 96.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(96)], verbose_name='altura da logo (px)'),
        ),
    ]
