# Generated by Django 5.2.17 on 2026-08-22 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfig_logo_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 ou WebM, curto e sem som — ele toca sozinho e em silêncio. Acima de ~5 MB a página fica lenta no 4G.', upload_to='banners/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogv'])], verbose_name='vídeo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='posicao',
            field=models.CharField(choices=[('hero', 'Carrossel principal'), ('faixa', 'Faixa promocional'), ('secundario', 'Banner secundário'), ('produtos', 'Faixa de produtos (fotos com link)'), ('apresentacao', 'Apresentação (vídeo ou foto no topo)')], default='hero', max_length=20),
        ),
    ]
