# Generated by Django 5.2.17 on 2026-08-23 10:34

import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_banner_video_alter_banner_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='banners/', validators=[apps.core.models.validar_tamanho_imagem]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 ou WebM, curto e sem som — ele toca sozinho e em silêncio. Até 60 MB; acima de 8 MB a página fica lenta para quem abre no 4G.', upload_to='banners/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogv']), apps.core.models.validar_tamanho_video], verbose_name='vídeo'),
        ),
    ]
