# Generated by Django 5.2.17 on 2026-09-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_banner_imagem_alter_banner_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='assistente_ativo',
            field=models.BooleanField(default=False, verbose_name='assistente virtual ligada'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='assistente_boas_vindas',
            field=models.CharField(blank=True, default='Oi! Eu sou a Silvinha, da AgroCampo. Posso ajudar a escolher um produto ou tirar dúvida sobre entrega?', max_length=200, verbose_name='primeira mensagem'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='assistente_imagem',
            field=models.ImageField(blank=True, help_text='Quadrada, de preferência. Sem imagem aparece a inicial do nome.', upload_to='site/', verbose_name='foto / avatar'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='assistente_instrucoes',
            field=models.TextField(blank=True, help_text="O que ela deve saber ou evitar. Ex.: 'não prometa prazo para cidades fora da lista', 'sugira ração Golden para cães adultos'.", verbose_name='orientações extras'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='assistente_nome',
            field=models.CharField(default='Silvinha', max_length=40, verbose_name='nome da assistente'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='aistudio.google.com › Get API key. Fica só no servidor.', max_length=200, verbose_name='Gemini · chave da API'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='gemini_modelo',
            field=models.CharField(blank=True, default='gemini-3.6-flash', max_length=60, verbose_name='Gemini · modelo'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_auto_ativo',
            field=models.BooleanField(default=False, help_text='Usa uma sessão do WhatsApp Web controlada pelo servidor. Esse formato não é oficial e o número pode ser banido pelo WhatsApp.', verbose_name='enviar avisos de pedido pelo WhatsApp automaticamente'),
        ),
    ]
