# Generated by Django 5.2.17 on 2026-09-21 09:25

import django.core.validators
from django.db import migrations, models


def logo_maior(apps, schema_editor):
    """Quem ainda estava no padrão antigo (46 px) sobe para o novo (64 px).
    Quem ajustou à mão fica como está."""
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(logo_altura=46).update(logo_altura=64)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_assistente_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='layout_home',
            field=models.CharField(choices=[('vitrine', 'Vitrine (carrossel de imagens, menu escuro)'), ('classico', 'Clássico (hero com texto sobre vermelho)')], default='vitrine', help_text='Trocar aqui muda o cabeçalho e a ordem dos blocos da home na hora.', max_length=12, verbose_name='estilo da home'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_altura',
            field=models.PositiveIntegerField(default=64, help_text='No celular ela encolhe sozinha. Entre 24 e 120.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(120)], verbose_name='altura da logo (px)'),
        ),
        migrations.RunPython(logo_maior, migrations.RunPython.noop),
    ]
