# Generated by Django 5.2.17 on 2026-09-21 10:16

import django.db.models.deletion
from django.db import migrations, models


def assinatura_sem_desconto(apps, schema_editor):
    """Decisão de 21/09: por padrão a assinatura não dá desconto. Quem estava
    no padrão antigo (10%) vai para 0; valor ajustado à mão fica."""
    SiteConfig = apps.get_model("core", "SiteConfig")
    SiteConfig.objects.filter(desconto_assinatura_padrao=10).update(desconto_assinatura_padrao=0)



class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_marca_sucesso_alter_produto_destaque'),
        ('core', '0012_layout_home_e_logo_maior'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='capa_apresentacao_ativa',
            field=models.BooleanField(default=False, help_text='O bloco grande de vídeo. Desligado, o carrossel abre a home sozinho.', verbose_name='mostrar o banner de apresentação (vídeo/foto)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='capa_slides_ativa',
            field=models.BooleanField(default=True, verbose_name='mostrar o carrossel de slides'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='home_ordem',
            field=models.CharField(blank=True, default='sucessos,ouro,prata,bronze,especies,categorias,faixas,oferta,promocoes,destaques,lancamentos,assinatura,porque,blog,newsletter,marcas', max_length=400, verbose_name='ordem das seções da home'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='desconto_assinatura_padrao',
            field=models.PositiveIntegerField(default=0, help_text='0 desliga o desconto: a assinatura vira só comodidade de entrega.', verbose_name='desconto padrão da assinatura (%)'),
        ),
        migrations.CreateModel(
            name='PromocaoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=120)),
                ('texto', models.TextField(blank=True, help_text='Condições, validade, o que quiser dizer.')),
                ('imagem', models.ImageField(blank=True, help_text='Opcional.', upload_to='promocoes/')),
                ('link', models.CharField(blank=True, max_length=300)),
                ('texto_botao', models.CharField(blank=True, default='Aproveitar', max_length=40)),
                ('cor_fundo', models.CharField(default='#D62B20', max_length=20)),
                ('inicio', models.DateTimeField(verbose_name='visível a partir de')),
                ('fim', models.DateTimeField(verbose_name='visível até')),
                ('posicao', models.CharField(default='sucessos', help_text='Aparece logo depois desta seção.', max_length=20, verbose_name='posição na home')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(blank=True, help_text='Opcional: puxa a foto e o link do produto quando não houver imagem/link próprios.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_destaque', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'promoção em destaque',
                'verbose_name_plural': 'promoções em destaque',
                'ordering': ['ordem', '-inicio'],
            },
        ),
        migrations.RunPython(assinatura_sem_desconto, migrations.RunPython.noop),
    ]
