# Generated by Django 5.2.17 on 2026-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_siteconfig_capa_apresentacao_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='assinatura_visivel',
            field=models.BooleanField(default=True, help_text='Desligado, some do menu, dos cards, do produto e da home. As assinaturas já feitas continuam sendo processadas.', verbose_name='mostrar a assinatura na loja'),
        ),
    ]
