# Generated by Django 5.2.17 on 2026-09-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_assinatura_visivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='posicao',
            field=models.CharField(choices=[('hero', 'Carrossel principal'), ('faixa', 'Faixa promocional'), ('secundario', 'Oferta em destaque (cartaz na home)'), ('produtos', 'Faixa de produtos (fotos com link)'), ('apresentacao', 'Vídeo ou foto de apresentação (entra no carrossel)')], default='hero', max_length=20),
        ),
    ]
