# Generated by Django 5.2.17 on 2026-09-21 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rotulos_posicao_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='entrega_hora_limite',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), help_text='Pedido pago depois desta hora conta como do dia seguinte. Vazio: o dia do pedido conta inteiro.', null=True, verbose_name='pedidos até (hora de corte)'),
        ),
    ]
