# Generated by Django 5.2.17 on 2026-10-05 10:48

from django.db import migrations, models


def nomes_das_linhas(apps, schema_editor):
    """As linhas Ouro/Prata/Bronze passam a se chamar Super Premium, Premium e
    uma terceira ainda sem nome — editáveis em Configurações › Vitrines."""
    SiteConfig = apps.get_model("core", "SiteConfig")
    for config in SiteConfig.objects.all():
        config.linha_ouro_nome = config.linha_ouro_nome or "Super Premium"
        config.linha_prata_nome = config.linha_prata_nome or "Premium"
        if config.vitrine_ouro_titulo in ("", "Mais vendidos — Linha Ouro"):
            config.vitrine_ouro_titulo = "Mais vendidos — Super Premium"
        if config.vitrine_prata_titulo in ("", "Mais vendidos — Linha Prata"):
            config.vitrine_prata_titulo = "Mais vendidos — Premium"
        if config.vitrine_bronze_titulo == "Mais vendidos — Linha Bronze":
            config.vitrine_bronze_titulo = "Mais vendidos — Linha 3"
        config.save()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hora_de_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='linha_bronze_nome',
            field=models.CharField(blank=True, default='', help_text='Ainda sem nome definido — escreva quando decidir.', max_length=40, verbose_name='nome da 3ª linha'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linha_ouro_nome',
            field=models.CharField(blank=True, default='Super Premium', help_text='A linha mais alta. Vazio esconde o selo nos produtos.', max_length=40, verbose_name='nome da 1ª linha'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linha_prata_nome',
            field=models.CharField(blank=True, default='Premium', max_length=40, verbose_name='nome da 2ª linha'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='vitrine_bronze_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Linha 3', max_length=60),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='vitrine_ouro_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Super Premium', max_length=60),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='vitrine_prata_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Premium', max_length=60),
        ),
        migrations.RunPython(nomes_das_linhas, migrations.RunPython.noop),
    ]
