# Generated by Django 5.2.17 on 2026-10-05 12:23

from django.db import migrations, models


def terceira_linha_especial(apps, schema_editor):
    """A terceira linha ganhou nome: Especial (as outras são Premium e Super
    Premium). Só preenche quem ainda estava sem nome."""
    SiteConfig = apps.get_model("core", "SiteConfig")
    for config in SiteConfig.objects.all():
        if not config.linha_bronze_nome.strip():
            config.linha_bronze_nome = "Especial"
        if config.vitrine_bronze_titulo in ("", "Mais vendidos — Linha 3"):
            config.vitrine_bronze_titulo = "Mais vendidos — Especial"
        config.save()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_linhas_proteina_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='linha_bronze_nome',
            field=models.CharField(blank=True, default='Especial', help_text='Vazio esconde o selo dos produtos desta linha.', max_length=40, verbose_name='nome da 3ª linha'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='vitrine_bronze_titulo',
            field=models.CharField(blank=True, default='Mais vendidos — Especial', max_length=60),
        ),
        migrations.RunPython(terceira_linha_especial, migrations.RunPython.noop),
    ]
