# Generated by Django 5.2.17 on 2026-10-10 12:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def iniciar_exibicao(apps, schema_editor):
    # O destino antigo permanece automático; a faixa passa a preservar as
    # bordas dos cartazes já cadastrados, sem exigir novo envio de mídia.
    apps.get_model('core', 'SiteConfig').objects.using(schema_editor.connection.alias).update(
        banners_padronizar=True, banners_formato='16/5',
    )
    apps.get_model('core', 'Banner').objects.using(schema_editor.connection.alias).update(
        tipo_destino='automatico', tempo_exibicao=Decimal('6.5'),
    )


def voltar_exibicao(apps, schema_editor):
    apps.get_model('core', 'SiteConfig').objects.using(schema_editor.connection.alias).update(banners_padronizar=False)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_lixeira_de_produtos'),
        ('core', '0019_cadastro_sem_listas_fechadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='categoria_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners_destino', to='catalog.categoria', verbose_name='categoria de destino'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tempo_exibicao',
            field=models.DecimalField(decimal_places=1, default=Decimal('6.5'), help_text='De 1 a 300 segundos por imagem ou vídeo. O vídeo repete até terminar esse tempo.', max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='tempo de exibição (segundos)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tipo_destino',
            field=models.CharField(choices=[('automatico', 'Automático (link ou primeiro produto)'), ('link', 'Link informado'), ('produtos', 'Produtos selecionados do catálogo'), ('categoria', 'Categoria do catálogo'), ('catalogo', 'Catálogo completo')], default='automatico', max_length=12, verbose_name='ao clicar, abrir'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banners_formato',
            field=models.CharField(choices=[('16/5', 'Faixa — 1600 × 500 px (recomendado)'), ('16/9', 'Paisagem — 1600 × 900 px'), ('2/1', 'Intermediário — 1600 × 800 px')], default='16/5', help_text='Medidas sugeridas para criar a arte. A faixa se adapta à largura do computador e do celular.', max_length=10, verbose_name='tamanho da faixa'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='banners_padronizar',
            field=models.BooleanField(default=True, help_text='Sim: todos usam a mesma moldura, sem cortar a arte. Não: cada imagem ou vídeo mantém sua proporção original.', verbose_name='padronizar tamanho (modo faixa)'),
        ),
        migrations.RunPython(iniciar_exibicao, voltar_exibicao),
    ]
