# Generated by Django 5.2.17 on 2026-08-20 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('cor', models.CharField(default='#D62B20', max_length=20)),
            ],
            options={
                'verbose_name': 'categoria do blog',
                'verbose_name_plural': 'categorias do blog',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('titulo', models.CharField(max_length=200)),
                ('capa', models.ImageField(blank=True, upload_to='blog/')),
                ('resumo', models.CharField(blank=True, max_length=250)),
                ('conteudo', models.TextField(help_text='Aceita HTML simples.')),
                ('tempo_leitura', models.PositiveIntegerField(default=4, verbose_name='tempo de leitura (min)')),
                ('destaque', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.categoriapost')),
                ('produtos_relacionados', models.ManyToManyField(blank=True, related_name='posts', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-publicado_em'],
            },
        ),
    ]
