# Generated by Django 5.2.17 on 2026-08-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('frequencia_dias', models.PositiveIntegerField(choices=[(30, 'A cada 30 dias'), (60, 'A cada 60 dias'), (90, 'A cada 90 dias')], default=30)),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço congelado no momento da assinatura.', max_digits=10)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('inadimplente', 'Pagamento pendente')], default='ativa', max_length=20)),
                ('proxima_entrega', models.DateField(db_index=True)),
                ('pausada_ate', models.DateField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=200)),
                ('falhas_consecutivas', models.PositiveIntegerField(default=0)),
                ('cartao', models.ForeignKey(blank=True, help_text='Cartão tokenizado usado nas cobranças recorrentes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='payments.cartaotokenizado')),
                ('endereco_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='accounts.endereco')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='catalog.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CicloAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero_ciclo', models.PositiveIntegerField(default=1)),
                ('data_prevista', models.DateField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('cobrando', 'Processando cobrança'), ('pago', 'Pago'), ('falhou', 'Falha na cobrança'), ('pulado', 'Pulado pelo cliente'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('erro', models.CharField(blank=True, max_length=250)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='subscriptions.assinatura')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclo_assinatura', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'ciclo da assinatura',
                'verbose_name_plural': 'ciclos das assinaturas',
                'ordering': ['-data_prevista'],
                'unique_together': {('assinatura', 'numero_ciclo')},
            },
        ),
    ]
