# Generated by Django 5.2.17 on 2026-09-21 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_produto_linha_alter_produto_unidade_variacaoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaAssistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('sessao', models.CharField(db_index=True, max_length=64)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('falhou', models.BooleanField(default=False)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('produto', models.ForeignKey(blank=True, help_text='Página em que a pergunta foi feita, se era de produto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_assistente', to='catalog.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_assistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversa da assistente',
                'verbose_name_plural': 'conversas da assistente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
