# Generated by Django 5.2.17 on 2026-08-22 13:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=90)),
                ('uf', models.CharField(default='BA', max_length=2, verbose_name='UF')),
                ('sede', models.BooleanField(default=False, help_text='A cidade da loja. Costuma ter frete e prazo próprios.', verbose_name='cidade sede')),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor do frete')),
                ('frete_gratis_acima_de', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio usa o valor global da loja. 0 desliga o frete grátis aqui.', max_digits=10, null=True, verbose_name='frete grátis acima de')),
                ('dias_entrega', models.CharField(blank=True, help_text='Dias da semana separados por vírgula (0=segunda … 6=domingo). Ex.: 4 entrega só às sextas. Vazio = todos os dias úteis.', max_length=20, verbose_name='dias de entrega')),
                ('horario_a_partir_de', models.TimeField(blank=True, help_text='Vazio usa o horário padrão da loja.', null=True, verbose_name='entregas a partir de')),
                ('prazo_dias', models.PositiveIntegerField(default=1, help_text='Dias até a entrega, contados do primeiro dia disponível.', verbose_name='prazo (dias)')),
                ('observacao', models.CharField(blank=True, help_text='Aviso exibido ao cliente no checkout.', max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True, verbose_name='atende esta cidade')),
            ],
            options={
                'verbose_name': 'cidade atendida',
                'verbose_name_plural': 'cidades atendidas',
                'ordering': ['-sede', 'ordem', 'nome'],
                'unique_together': {('nome', 'uf')},
            },
        ),
        migrations.CreateModel(
            name='RegraEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('momento', models.CharField(choices=[('carrinho', 'No carrinho'), ('checkout', 'Na escolha do endereço'), ('pagamento', 'Na tela de pagamento'), ('confirmacao', 'Depois de finalizar')], default='checkout', max_length=20)),
                ('icone', models.CharField(default='caminhao', help_text='caminhao, relogio, info, alerta, escudo.', max_length=30)),
                ('destaque', models.BooleanField(default=False, help_text='Use para avisos que o cliente precisa mesmo ler.', verbose_name='destacar em amarelo')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(blank=True, help_text='Vazio mostra para todas as cidades.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='shipping.cidade')),
            ],
            options={
                'verbose_name': 'aviso de entrega',
                'verbose_name_plural': 'avisos de entrega',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(help_text='Como o cliente conhece o lugar — mesmo que não exista no mapa.', max_length=120)),
                ('frete_adicional', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Somado ao frete da cidade.', max_digits=10, verbose_name='acréscimo no frete')),
                ('acesso_por_barco', models.BooleanField(default=False, help_text='Ilhas e localidades que dependem de travessia.', verbose_name='acesso por barco / travessia')),
                ('prazo_extra_dias', models.PositiveIntegerField(default=0, verbose_name='dias a mais no prazo')),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='shipping.cidade')),
            ],
            options={
                'verbose_name': 'localidade',
                'verbose_name_plural': 'localidades',
                'ordering': ['cidade__nome', 'nome'],
                'unique_together': {('cidade', 'nome')},
            },
        ),
    ]
