# Generated by Django 5.2.17 on 2026-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='dias_entrega',
            field=models.CharField(blank=True, help_text='Os dias em que o carro vai para esta cidade, separados por vírgula (0=segunda … 6=domingo). Ex.: 4 = só às sextas. Vazio = todos os dias úteis.', max_length=20, verbose_name='dias de viagem / entrega'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=1, help_text='Dias entre o pedido e a viagem. 0 = sai no mesmo dia se o pedido entrar antes da hora de corte; 1 = no dia seguinte, e assim por diante. Depois disso a data cai no próximo dia de viagem.', verbose_name='antecedência (dias)'),
        ),
    ]
