# Generated by Django 5.2.17 on 2026-08-20 03:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('grupo', models.CharField(choices=[('passeriforme', 'Passeriformes'), ('psitacideo', 'Psitacídeos'), ('pet', 'Pets'), ('rural', 'Rural e produção'), ('outro', 'Outros')], default='outro', max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='especies/')),
                ('icone', models.CharField(blank=True, max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('destaque_home', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'espécie',
                'verbose_name_plural': 'espécies',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, upload_to='marcas/')),
                ('descricao', models.TextField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('destaque', models.BooleanField(default=True, verbose_name='exibir na vitrine de marcas')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text='Emoji exibido nos atalhos da home.', max_length=10)),
                ('imagem', models.ImageField(blank=True, upload_to='categorias/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('exibir_no_menu', models.BooleanField(default=True)),
                ('destaque_home', models.BooleanField(default=False, verbose_name='atalho na home')),
                ('publicado', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhas', to='catalog.categoria', verbose_name='categoria pai')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='SKU')),
                ('resumo', models.CharField(blank=True, max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True, help_text='Um benefício por linha — vira lista na página do produto.')),
                ('composicao', models.TextField(blank=True, verbose_name='composição / tabela nutricional')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permite_assinatura', models.BooleanField(default=False, verbose_name='disponível para assinatura')),
                ('desconto_assinatura', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='desconto da assinatura (%)')),
                ('unidade', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('l', 'Litro'), ('pct', 'Pacote')], default='un', max_length=5)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=5, help_text='Abaixo disso o painel emite alerta.')),
                ('destaque', models.BooleanField(default=False, verbose_name='mais vendido')),
                ('lancamento', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('vendas', models.PositiveIntegerField(default=0, editable=False)),
                ('promocao_ate', models.DateTimeField(blank=True, help_text='Data-limite da oferta (ativa o contador).', null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.categoria')),
                ('especies', models.ManyToManyField(blank=True, related_name='produtos', to='catalog.especie', verbose_name='espécies indicadas')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalog.marca')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste manual')], max_length=10)),
                ('quantidade', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('pedido_referencia', models.CharField(blank=True, max_length=40)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desejos', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desejado_por', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'item da lista de desejos',
                'verbose_name_plural': 'lista de desejos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('comentario', models.TextField(blank=True)),
                ('aprovada', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('legenda', models.CharField(blank=True, max_length=140)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'imagem do produto',
                'verbose_name_plural': 'imagens do produto',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['publicado', 'destaque'], name='catalog_pro_publica_e9ecc4_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'publicado'], name='catalog_pro_categor_284f4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listadesejos',
            unique_together={('usuario', 'produto')},
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('produto', 'autor')},
        ),
    ]
