# Generated by Django 5.2.17 on 2026-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='credito_imagem',
            field=models.CharField(blank=True, help_text='Autor e licença — obrigatório para fotos sob Creative Commons.', max_length=250, verbose_name='crédito da imagem'),
        ),
        migrations.AddField(
            model_name='especie',
            name='nome_cientifico',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
