# Generated by Django 5.2.17 on 2026-08-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_especie_credito_imagem_especie_nome_cientifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, choices=[('racao', 'Ração e alimentação'), ('ave', 'Aves e pássaros'), ('rural', 'Rural e fazenda'), ('saude', 'Saúde animal'), ('acessorio', 'Acessórios'), ('jardim', 'Casa e jardim'), ('cao', 'Cães'), ('gato', 'Gatos'), ('peixe', 'Peixes'), ('semente', 'Sementes'), ('pata', 'Genérico (pata)')], help_text='Ícone vetorial exibido no menu e nos atalhos da home.', max_length=20, verbose_name='ícone'),
        ),
    ]
