# Generated by Django 5.2.17 on 2026-08-21 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categoria_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='desconto_assinatura',
        ),
        migrations.AddField(
            model_name='produto',
            name='desconto_assinatura_proprio',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe vazio para seguir o percentual global da loja (Configuração da loja › desconto padrão da assinatura). Preencha só quando este produto precisar de um desconto diferente.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='desconto da assinatura (%)'),
        ),
    ]
