# Generated by Django 5.2.17 on 2026-08-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_produto_desconto_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='compra_verificada',
            field=models.BooleanField(default=True, help_text='Marcado quando a avaliação veio de quem comprou o produto.', verbose_name='compra verificada'),
        ),
    ]
