# Generated by Django 5.2.17 on 2026-08-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_converte_emoji_para_icone_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='linha',
            field=models.CharField(blank=True, choices=[('ouro', 'Linha Ouro'), ('prata', 'Linha Prata'), ('bronze', 'Linha Bronze')], db_index=True, help_text='Ouro, Prata ou Bronze. Vazio deixa o produto fora das vitrines por linha.', max_length=10, verbose_name='linha'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('pct', 'Pacote')], default='un', max_length=5),
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Ex.: 2 para 2kg, 500 para 500g.', max_digits=8, verbose_name='quantidade')),
                ('unidade', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'L'), ('ml', 'mL'), ('un', 'un')], default='kg', max_length=4)),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='SKU')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, help_text='Foto desta apresentação. Vazio usa a foto principal do produto.', upload_to='produtos/')),
                ('padrao', models.BooleanField(default=False, help_text='A que vem marcada ao abrir o produto.', verbose_name='opção padrão')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'variação do produto',
                'verbose_name_plural': 'variações do produto',
                'ordering': ['ordem', 'preco'],
                'unique_together': {('produto', 'quantidade', 'unidade')},
            },
        ),
    ]
