# Generated by Django 5.2.17 on 2026-09-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_produto_linha_alter_produto_unidade_variacaoproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='sucesso',
            field=models.BooleanField(default=False, help_text='Atalho para não marcar produto por produto.', verbose_name='todos os produtos desta marca em Maiores sucessos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Entra na vitrine Maiores sucessos da home. Marcas inteiras: no cadastro da marca.', verbose_name='maior sucesso'),
        ),
    ]
