# Generated by Django 5.2.17 on 2026-10-02 11:40

from django.db import migrations, models


def produtos_existentes_sem_controle(apps, schema_editor):
    """Pedido do lojista (02/10): o catálogo foi cadastrado sem quantidade, então
    tudo que já existe passa a vender sem controle de estoque — senão a loja
    inteira aparece esgotada. Produto novo nasce com controle normal."""
    Produto = apps.get_model("catalog", "Produto")
    Produto.objects.update(sem_controle_estoque=True)



class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_marca_sucesso_alter_produto_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sem_controle_estoque',
            field=models.BooleanField(default=False, help_text='Para quem vende sob encomenda ou não conta quantidade: o produto fica sempre disponível para compra e a loja combina a entrega. O número de estoque abaixo passa a ser só referência.', verbose_name='sem controle de estoque'),
        ),
        migrations.RunPython(produtos_existentes_sem_controle, migrations.RunPython.noop),
    ]
