# Generated by Django 5.2.17 on 2026-10-05 10:48

import django.core.validators
from django.db import migrations, models


def estoque_infinito_para_todos(apps, schema_editor):
    """Decisão do lojista (05/10): a loja inteira vende sem contagem. Se faltar
    na separação, a equipe chama o cliente no WhatsApp. Para contar um produto
    específico, basta desmarcar a opção no cadastro dele."""
    Produto = apps.get_model("catalog", "Produto")
    Produto.objects.update(sem_controle_estoque=True)



class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_sem_controle_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='proteina',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Aparece numa faixa azul sobre a foto, como no rótulo da ração. Vazio não mostra nada.', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='% de proteína'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sem_controle_estoque',
            field=models.BooleanField(default=True, help_text='Padrão da loja: o produto fica sempre disponível para compra e, se faltar, a equipe fala com o cliente pelo WhatsApp para trocar ou devolver. Desmarque só para contar quantidade de verdade.', verbose_name='sem controle de estoque'),
        ),
        migrations.RunPython(estoque_infinito_para_todos, migrations.RunPython.noop),
    ]
