# Generated by Django 5.2.17 on 2026-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_linha_cadastravel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sem_controle_estoque',
            field=models.BooleanField(default=True, help_text='Padrão da loja: o produto fica sempre disponível para compra e, se faltar na separação, a equipe fala com o cliente pelo WhatsApp para trocar ou devolver. Desmarque só para contar quantidade de verdade.', verbose_name='sem controle de estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade',
            field=models.CharField(default='un', help_text='un, kg, g, L… ou a que a loja usar.', max_length=5),
        ),
    ]
