# Generated by Django 5.2.17 on 2026-10-08 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_cadastro_sem_listas_fechadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhaproduto',
            name='selo_imagem',
            field=models.ImageField(blank=True, help_text='PNG com fundo transparente. Vazio usa a medalha desenhada pelo site.', upload_to='selos/', verbose_name='imagem do selo (PNG)'),
        ),
        migrations.AddField(
            model_name='linhaproduto',
            name='selo_tamanho',
            field=models.PositiveSmallIntegerField(default=64, help_text='Medida no card da vitrine; na página do produto ele cresce na mesma proporção. Entre 24 e 220 — o padrão é 64.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(220)], verbose_name='tamanho do selo (px)'),
        ),
    ]
