# Generated by Django 5.2.17 on 2026-10-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_cor_livre_da_linha'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='excluido_em',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='mandado para a lixeira em'),
        ),
    ]
