# Generated by Django 5.2.17 on 2026-08-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('publico', models.CharField(choices=[('cliente', 'Cliente'), ('lojista', 'Lojista')], default='cliente', max_length=15)),
                ('tipo', models.CharField(choices=[('pagamento_confirmado', 'Pagamento confirmado'), ('pagamento_recusado', 'Pagamento recusado'), ('pedido_novo', 'Novo pedido recebido'), ('pedido_aprovado', 'Pedido aprovado'), ('pedido_recusado', 'Pedido recusado'), ('pedido_enviado', 'Pedido enviado'), ('estorno', 'Estorno processado'), ('assinatura_renovada', 'Assinatura renovada'), ('assinatura_falhou', 'Falha na assinatura'), ('estoque_baixo', 'Estoque baixo'), ('geral', 'Geral')], default='geral', max_length=30)),
                ('nivel', models.CharField(choices=[('sucesso', 'Sucesso'), ('info', 'Informação'), ('alerta', 'Alerta'), ('erro', 'Erro')], default='info', max_length=15)),
                ('titulo', models.CharField(max_length=140)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_por_email', models.BooleanField(default=False)),
                ('enviada_por_whatsapp', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Vazio + público=lojista significa notificação para toda a equipe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
