# Generated by Django 5.2.17 on 2026-09-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('orders', '0004_itempedido_variacao_itempedido_variacao_rotulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('numero', models.CharField(help_text='Só dígitos, com DDI.', max_length=20)),
                ('texto', models.TextField()),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('falhou', 'Falhou'), ('ignorada', 'Ignorada')], max_length=10)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_whatsapp', to='notifications.notificacao')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_whatsapp', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'mensagem de WhatsApp',
                'verbose_name_plural': 'mensagens de WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
    ]
